<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Http;

function currentUser()
{
    return auth()->user();
}

function getCountries()
{
    $countries = Http::get('https://restcountries.com/v3.1/all?fields=name,idd,flags,currencies,capital');
    return $countries;
}

function redirectback()
{
    return redirect()->back();
}

function currentUserPermissions(): array | null
{
    $permissions = \App\Models\Permission::select('name')
        ->whereRelation('roles', 'name', auth()->user()->current_role)
        ->orWhereRelation('users', 'id', Auth::id())
        ->pluck('name')
        ->toArray();
    return $permissions;
}

function statusColor($status)
{
    // $color = "bg-gray-500 text-gray-50";
    switch ($status) {
        case 'active':
            $color = "border-green-500 text-green-500";
            break;
        case 'created':
            $color = "border-green-300 text-green-300";
            break;
        case 'accepted':
            $color = "border-green-500 text-green-500";
            break;
        case 'onLeave':
            $color = "border-orange-400 text-orange-400";
            break;
        case 'credit':
            $color = "border-green-500 text-green-500";
            break;
        case 'debit':
            $color = "border-red-500 text-red-500";
            break;
        case 'expired':
            $color = "border-red-500 text-red-500";
            break;
        case 'expiring':
            $color = "border-yellow-500 text-yellow-500";
            break;
        case 'graduated':
            $color = "border-red-900 text-red-900";
            break;
        default:
            $color = "bg-gray-500 text-gray-500 font-medium";
            break;
    }

    return $color;
}

function nigeriaState(): array
{
    return [
        "Abia",
        "Adamawa",
        "Akwa Ibom",
        "Anambra",
        "Bauchi",
        "Bayelsa",
        "Benue",
        "Borno",
        "Cross River",
        "Delta",
        "Ebonyi",
        "Edo",
        "Ekiti",
        "Enugu",
        "Gombe",
        "Imo",
        "Jigawa",
        "Kaduna",
        "Kano",
        "Katsina",
        "Kebbi",
        "Kogi",
        "Kwara",
        "Lagos",
        "Nasarawa",
        "Niger",
        "Ogun",
        "Ondo",
        "Osun",
        "Oyo",
        "Plateau",
        "Rivers",
        "Sokoto",
        "Taraba",
        "Yobe",
        "Zamfara",
        "Federal Capital Territory",
    ];
}

function userNameAbbr($pre): string
{
    if ($pre == "superadmin") {
        return "SAD";
    } else if ($pre == "admin") {
        return "ADM";
    } else if ($pre == "dean") {
        return "DEAN";
    } else if ($pre == "hod") {
        return "HOD";
    } else if ($pre == "lecturer") {
        return "LEC";
    } else {
        return "STU";
    }
}

function getUsersIdsByRole($val): array
{
    $ids = \App\Models\User::select('id')->where('current_role_id', $val)->pluck('id')->toArray();
    return $ids;
}
function getUsersParkIdsByRole($val): array
{
    $ids = \App\Models\User::select('park_id')->where('current_role_id', $val)->pluck('park_id')->toArray();
    return $ids;
}

function getUsersByRole($val): array | object
{
    $users = \App\Models\User::select('id', 'name')->where('current_role_id', $val)->get();
    return $users;
}

function isTimeToRenew($com)
{
    // $date1 = now()->format('Y-m-d');
    $date2 = date_create($com);
    $diff = date_diff(now(), $date2);
    return intval($diff->format("%R%a"));
}

function profilePicture(object $user): string
{
    return $user->avatar ? asset('storage/' . $user->avatar) : asset('img/avatar.png');
}

// SELECT provinces.id, provinces.state, COUNT(cities.province_id) AS cities FROM cities LEFT JOIN provinces ON cities.province_id = provinces.id GROUP BY cities.province_id;

function cities(): array
{
    return array(
        "abia" => [
            "ABA",
            "AMAEKE",
            "AROCHUKWU",
            "IKWUANO",
            "ISIALA NGWA NORTH",
            "ISIALA NGWA SOUTH",
            "OHAFIA",
            "UMUAHIA",
            "UMUDIKE",
        ],
        "adamawa" => [
            "GOMBI",
            "HONG",
            "MAYO ",
            "MUBI",
            "NGURORE",
            "NUMAN",
            "SONG",
            "YOLA",
            "YOLA - CENTRAL LOCATIONS",
        ],
        "akwa-ibom" => [
            "ABAK",
            "ADAGHA ANYAN",
            "AFAHA OBONG JUNCTION",
            "EKET",
            "ETIM EKPO",
            "ETINAN",
            "IBENO",
            "IKOT ABASI",
            "IKOT EKPENE",
            "IKOT OSURUA",
            "MKPAT ENIN",
            "OBO ANNANG MARKET",
            "ORON",
            "QUA IBOE TERMINAL / QIT",
            "URUA AKPAN IBOM",
            "URUA OFFIONG",
            "UYO - ABAK ROAD",
            "UYO - AKA ROAD",
            "UYO - BANKING LAYOUT",
            "UYO - EWET HOUSING ESTATE",
            "UYO - FOUR (4) LANE",
            "UYO - IBB",
            "UYO - IKOT EKPENE ROAD",
            "UYO - NSIKAK EDUOK",
            "UYO - NWANIBA",
            "UYO - ORON ROAD",
            "UYO - OSONGAMA",
            "UYO - PLAZA",
            "UYO - SECRETARIAT",
            "UYO - SHELTER AFRIQUE",
            "UYO - SHELTER AFRIQUE EXTENSION",
            "UYO - UDO UDOMA",
            "UYO - UNIUYO PERMANENT SITE",
            "UYO - UNIUYO TOWN CAMPUS",
        ],
        "anambra" => [
            "ABAGANA",
            "ACHALLA / AKA",
            "AMAWBIA / AWKA",
            "ANAMBRA EAST",
            "ANAMBRA WEST",
            "AWKA TOWN",
            "AYAMELUM",
            "DUNUKOFIA",
            "EKWULOBIA",
            "IHIALA",
            "NISE / AWKA",
            "NKPOR",
            "NNEWI - ALOR",
            "NNEWI - AWADA LAYOUT",
            "NNEWI - NNEWI",
            "NNEWI - OBA",
            "NNEWI - OBOSI",
            "NNEWI - OJOTO",
            "NNEWI - ORAIFITE",
            "NNEWI - ORAUKWU",
            "NNEWI - OZUBULU",
            "NNEWI - NNOBI",
            "NNEWI - UTUH",
            "NNEWI - ABATETE",
            "NNEWI - AMICHI",
            "NNEWI - ICHI 1",
            "NNEWI - OGIDI",
            "OGBARU",
            "OGIDI / AWKA",
            "ONITSHA",
            "ONITSHA - CENTRAL LO",
            "CATIONSONITSHA - GRA",
            "OYI",
            "UMUOKPE / AWKA",
        ],
        "bauchi" => [
            "ALKALERI",
            "AWALA",
            "BAUCHI CENTRAL DISTRICT",
            "BAUCHI NORTH DISTRICT",
            "BAUCHI SOUTH DISTRICT",
            "CENTRAL MARKET",
            "DARAZO",
            "FADAMAR MADA",
            "GIDA DUBU",
            "IBRAHIM BAKO",
            "KATAGUM / AZARE",
            "NEW GRA / WUNTIN DADA",
            "OLD GRA",
            "RAILWAY / FED LOW COST",
            "WUNTI",
            "YAN DOKA",
            "YELWA / FED POLY",
        ],
        "bayelsa" => [
            "AMASSOMA",
            "BRASS",
            "EKEREMOR",
            "KIAMA",
            "KOLOKUMA / OPOKUMA",
            "NEMBE",
            "OGBIA",
            "OTUOKE",
            "SAGBAMA",
            "SOUTHERN IJAW",
            "WILBERFORCE ISLAND",
            "YENAGOA",
        ],
        "benue" => [
            "GBOKO",
            "KATSINA-ALA",
            "MAKURDI - CENTRAL LOCATIONS",
            "MAKURDI - BANK ROAD",
            "MAKURDI - AIRFORCE BASE",
            "MAKURDI - BENUE STATE UNIVERSITY",
            "MAKURDI - HIGH LEVEL",
            "MAKURDI - JUDGES QUARTERS",
            "MAKURDI - LOW LEVEL",
            "MAKURDI - MODERN MARKET",
            "MAKURDI - NEW GRA",
            "MAKURDI - NYIMA",
            "MAKURDI - OLD GRA",
            "MAKURDI - SECRETARIAT",
            "MAKURDI - UNIVERSITY OF AGRIC",
            "MAKURDI - WADATA",
            "MAKURDI - WURUKUM",
            "MKAR",
            "OTUKPO",
            "OTUKPA",
            "VANDEKYA",
            "YANDEV",
        ],
        "borno" => [
            "MAIDUGURI",
            "MONGUNO",
        ],
        "cross-river" => [
            "ABI",
            "AKAMKPA",
            "AKPABUYO",
            "BAKASSI",
            "BEKWARRA",
            "BIASE",
            "BOKI",
            "CALABAR",
            "CALABAR - MARINA",
            "ETUNG",
            "IKOM",
            "OBANLIKU",
            "OBUBRA",
            "OBUDU",
            "ODUKPANI",
            "OGOJA",
            "YAKUUR",
            "YALA",
        ],
        "delta" => [
            "WARRI - DECO ROAD",
            "ABRAKA - AJANOMI",
            "ABRAKA - DELSU CAMPUS 1",
            "ABRAKA - DELSU CAMPUS 2",
            "ABRAKA - DELSU CAMPUS 3",
            "ABRAKA - EKREJETA",
            "ABRAKA - ERHO",
            "ABRAKA - FSP / HOSPITAL ROAD",
            "ABRAKA - NEW ROAD",
            "ABRAKA - OJETA",
            "ABRAKA - OLD SAPELE AGBOR ROAD",
            "ABRAKA - ORIA",
            "ABRAKA - ORUARIVIE",
            "ABRAKA - OTORHO",
            "ABRAKA - POLICE STATION ROAD",
            "ABRAKA - UGHERE - URHUAGBESA",
            "ABRAKA - UMEGHE",
            "ABRAKA - UMONO ROAD",
            "ABRAKA - URHUOKA",
            "ABRAKA - WINNERS ROAD",
            "AGBOR - ABAVO",
            "AGBOR - ALERO",
            "AGBOR - ALIHAME",
            "AGBOR - BOJI BOJI",
            "AGBOR - EKUOMA",
            "AGBOR - IGBODO",
            "AGBOR - OBI",
            "AGBOR - OWA OYIBU",
            "AGBOR - UMUNEDE",
            "ALADJA",
            "ASABA - ABRAKA MARKET",
            "ASABA - ACHALA IBUSA",
            "ASABA - AKUEBULU",
            "ASABA -AKUOFOR",
            "ASABA - ANWAI",
            "ASABA - ASABA AIRPORT",
            "ASABA - ASABA - BENIN EXPRESS ROAD",
            "ASABA - BONSAAC",
            "ASABA - CABLE POINT",
            "ASABA - CAMP 74",
            "ASABA - DENNIS OSADEBE WAY",
            "ASABA - DLA ROAD",
            "ASABA - EZENEI",
            "ASABA - FEDERAL COLLEGE",
            "ASABA - GRA CORE AREA",
            "ASABA - HOUSING ESTATE",
            "ASABA - IBUSA ROAD",
            "ASABA - INFANT JESUS ROAD",
            "ASABA - JARRET",
            "ASABA - JESUS SAVES ROAD",
            "ASABA - JUNIC HOTEL AREA",
            "ASABA - KOKA JUNCTION",
            "ASABA - NNEBISI",
            "ASABA - OKPANAM",
            "ASABA - OKWE",
            "ASABA - SUMMIT",
            "SBRUMEDE",
            "EKU-EKU CENTRAL LOCATION",
            "EKU-EKU OBIARUKU ROAD",
            "EKU-EKU WARRI ROAD",
            "FUPRE",
            "ISELE",
            "KWALE - CENTRAL LOCATION",
            "OBIARUKU - CENTRAL LOCATION",
            "OBIARUKU - NOVENA UNIVERSITY",
            "OGHARA - NIGERIAN NAVY BASE",
            "OGHARA - OGHARA JUNCTION",
            "OGHARA - OGHARAFE",
            "OGHARA - OGHAREKI",
            "OGHARA - OVADE",
            "OGHARA - OTEFE",
            "OGWASHI",
            "OLEH - CENTRAL LOCATION",
            "OLEH - DELSU OLEH CAMPUS",
            "OTOR",
            "OVWIAN",
            "OZORO - DELTA STATE POLY",
            "OZORO - EMU OBIOGO ROAD",
            "OZORO - OZORO ROAD",
            "SAPELE - AJOGODO",
            "SAPELE - AKINTOLA",
            "SAPELE - AMUKPE",
            "SAPELE - GANA",
            "SAPELE - JESSE",
            "SAPELE - MOSOGAR",
            "SAPELE - NEW ROAD",
            "SAPELE - OGORODE",
            "SAPELE - OKPE ROAD",
            "SAPELE - UGBERIKOKO",
            "SAPELE - YORUBA ROAD",
            "UDU - ALADJA",
            "UDU - OFAGBE",
            "UDU - ORHUWORUN",
            "UDU - ORHUWORUN ROAD",
            "UDU - OTOR",
            "UDU - UDU EXPRESS",
            "UDU - USIEFRUN",
            "UGHELLI EKEREJEBOR ROAD",
            "UGHELLI - 1ST EMEKPA JUNCTION",
            "UGHELLI - EKUIGBO",
            "UGHELLI - GENERAL HOSPITAL",
            "UGHELLI - ISOKO ROAD",
            "UGHELLI - MARKET ROAD",
            "UGHELLI - OTERI",
            "UGHELLI - OTOVWODO JUNCTION",
            "UGHELLI - POST OFFICE",
            "UGHELLI - SOKAJI",
            "UGHELLI - ULOHO AVENUE",
            "UGHELLI - UPPER AFIESERE",
            "UMUNEDE",
            "WARRI - AIRPORT ROAD",
            "WARRI - EDJEBA",
            "WARRI - EFURUN",
            "WARRI - EKPAN",
            "WARRI - ENERHEN",
            "WARRI - GRA",
            "WARRI - JAKPA",
            "WARRI - JEDDO",
            "WARRI - N.P.A",
            "WARRI - OGUNU",
            "WARRI - OSUBI",
            "WARRI - P.T.I",
            "WARRI - REFINERY ROAD",
            "WARRI - UBEJI",
            "WARRI - UGWUANGWE",
        ],
        "ebonyi" => [
            "ABAKALIKI",
            "AFIKPO NORTH",
            "AFIKPO SOUTH - EDDA",
            "EZZA NORTH",
            "EZZA SOUTH",
            "IKWO",
            "ISHIELU",
            "IVO",
            "IZZI",
            "OHAOZARA",
            "OHAUKWU",
            "ONICHA",
        ],
        "edo" => [
            "AKOKO EDO",
            "BENIN - ADESUWA",
            "BENIN - ADUWAWA",
            "BENIN - AGBOR PARK",
            "BENIN - AKPAPAVA",
            "BENIN - BUMEZ",
            "BENIN - EKAE",
            "BENIN - EKENWAN",
            "BENIN - EKHOR",
            "BENIN - EKOSODIN",
            "BENIN - EKUKU",
            "BENIN - ERIARIA",
            "BENIN - ETETE",
            "BENIN - EVBOTUBE",
            "BENIN - EWEMADE VILLAGE",
            "BENIN - EYAEN",
            "BENIN - GRA",
            "BENIN - IDOGBO",
            "BENIN - IHOGBEN",
            "BENIN - IKPOBA HILL",
            "BENIN - IKPOKAN",
            "BENIN - IWOGBAN",
            "BENIN - LIMITS",
            "BENIN - MEDICAL ROAD",
            "BENIN - NEW BENIN MARKET",
            "BENIN - NPDC",
            "BENIN - OBE",
            "BENIN - OGBELAKA",
            "BENIN - OHOVBEOKAO",
            "BENIN - OKO-GBA",
            "BENIN - OLOGBO",
            "BENIN - OREGBENI",
            "BENIN - RING ROAD",
            "BENIN - SECRETARIAT",
            "BENIN - ST SAVIOUR",
            "BENIN - UGBEKUN",
            "BENIN - UGBOR",
            "BENIN - OGBOWO",
            "BENIN - UHUMWUIMWU",
            "BENIN - URHKWUOSA",
            "BENIN - URUBI",
            "BENIN - USE",
            "BENIN - USELU",
            "BENIN - UWELU",
            "EGOR - EGOR",
            "EGOR - ENVIRON CAMPS",
            "EGOR - OVIASUYI CAMP",
            "EKIADOLOR",
            "EKIADORO",
            "EKPOMA - UJOEHENLEN",
            "EKPOMA - AFUA",
            "EKPOMA - AMBROSE ALI UNIVERSITY",
            "EKPOMA - DEBOW",
            "EKPOMA - EBHOAKHUA",
            "EKPOMA - EGUARE",
            "EKPOMA - EMADO",
            "EKPOMA - IDUMEBO",
            "EKPOMA - IDUMEGBEDE",
            "EKPOMA - IHUMUDUMU",
            "EKPOMA - ILE",
            "EKPOMA - IRUEKPEN",
            "EKPOMA - OKPENU",
            "EKPOMA - ORIAFOR",
            "EKPOMA - OZALLA",
            "EKPOMA - PALMWELL",
            "EKPOMA - UJEMEN",
            "ESAN CENTRE",
            "ESAN SOUTH",
            "ESAN WEST",
            "ETSAKO CENTRAL",
            "ETSAKO EAST",
            "ETSAKO IGBIRA CAMP",
            "ETSAKO WEST",
            "ETSAKO - AGENEBODE",
            "ETSAKO - AIBOTSE",
            "ETSAKO - AIGIERE",
            "ETSAKO - AUCHI MARKET",
            "ETSAKO - AUCHI POLY CAMPUS 1",
            "ETSAKO - AUCHI POLY CAMPUS 2",
            "ETSAKO - AUCHI POLY CAMPUS 3",
            "ETSAKO - AZUKALA",
            "ETSAKO - FUGAR JUNCTION",
            "ETSAKO - IGBE ROAD",
            "ETSAKO - IRAOKHOR",
            "ETSAKO - ITSUKWI",
            "ETSAKO - IYEKHEI",
            "ETSAKO - JATTU JUNCTION",
            "ETSAKO - OGBONA",
            "ETSAKO - OKPELLA",
            "ETSAKO - SOUTH IBIE",
            "ETSAKO - UZANI",
            "IGUEBEN",
            "IKPOBA OKHA",
            "OKADA",
            "OKADA - CENTRAL LOCATION",
            "OKADA - ESTATE GATE",
            "OKADA - GRA",
            "OKADA - HOSTEL GATE",
            "OKADA - IGBINEDION",
            "OKADA - IGBOBAZUWA",
            "OKADA - IYARO",
            "OKADA - MAIN CAMPUS",
            "OKADA - NEW ROAD",
            "OKADA - OKADA VILLAGE",
            "OKADA - TEACHING HOSPITAL",
            "OLUKU",
            "ORHIONMWON",
            "OVIA NORTH EAST",
            "OVIA SOUTH WEST",
            "OWAN EAST",
            "OWAN WEST",
            "UBIAJA",
            "UGBOWO",
            "UGBOWO - ISIOHOR",
            "UGBOWO - ADOLOR COLLEGE ROAD",
            "UGBOWO - BDPA",
            "UGBOWO - EDPA",
            "UGBOWO - FEDERAL ROAD / OSASOGIE",
            "UGBOWO - OLUKU",
            "UGBOWO - S / T BARRACKS",
            "UGBOWO - TECHNICAL COLLEGE ROAD",
            "UGBOWO - UBTH",
            "UGBOWO - UNIBEN",
            "UGBOWO - USELU",
            "UGBOWO - UWAGBOE",
            "UGBOWO - UWASOTA",
            "UGBOWO - UWELU",
            "UHEN",
            "UROMI",
        ],
        "ekiti" => [
            "ADO EKITI",
            "AFE BABALOLA",
            "ARAMOKO",
            "EFON",
            "EFON - ALAAYE",
            "EKITI EAST",
            "EMURE",
            "GBONYIN",
            "IDO OSI",
            "IJERO",
            "IKERE",
            "IKOLE",
            "ILAWE",
            "ILEJEMEJE",
            "IREPODUN / IFELODUN",
            "ISE EKITI",
            "ISE / ORUN",
            "IWOROKO",
            "MOBA",
            "OMUO",
            "OTUN",
            "OYE",
        ],
        "enugu" => [
            "AGBANI",
            "ANINRI",
            "ANIRI",
            "AWGU",
            "ENUGU GARKI",
            "ENUGU TRANSEKULU",
            "ENUGU - ABAKPA NIKE",
            "ENUGU - CENTRAL LOCATION",
            "EZEAGU",
            "IGBO ETITI",
            "IGBO EZE NORTH",
            "IGBO EZE SOUTH",
            "ISI UZO",
            "ITUKU OZALLA",
            "NKANU EAST",
            "NKANU WEST",
            "NSUKKA",
            "NSUKKA - EDE OBALLA",
            "NSUKKA - EHA ALUMONA",
            "OJI RIVER",
            "UDENU",
            "UDI",
            "UZO - UWANI",
        ],
        "federal-capital-terirrtory" => [
            "ABAJI",
            "ABUJA AIRPORT ROAD - TECHNOLOGY VILLAGE",
            "ABUJA AIRPORT ROAD - CHIKA",
            "ABUJA AIRPORT ROAD - GOSA / SABON LUGBE",
            "ABUJA AIRPORT ROAD - KUCHINGORO",
            "ABUJA AIRPORT ROAD - KYAMI / CENTENARY CITY",
            "ABUJA AIRPORT ROAD - NNAMDI AZIKIWE AIRPORT",
            "ABUJA AIRPORT ROAD - PIWOYI",
            "ABUJA AIRPORT ROAD - PYAKASA",
            "ABUJA AIRPORT ROAD - RIVER PARK / TRADE MORE",
            "ABUJA AIRPORT ROAD - SAUKA / IMMIGRATION HQ",
            "APO CENTRAL",
            "APO LEGISLATIVE ZONE A",
            "APO LEGISLATIVE ZONE B",
            "APO LEGISLATIVE ZONE C",
            "APO LEGISLATIVE ZONE D",
            "APO LEGISLATIVE ZONE E",
            "APO MECHANIC VILLAGE",
            "APO RESETTLEMENT ZONE A",
            "APO RESETTLEMENT ZONE B",
            "APO RESETTLEMENT ZONE C",
            "APO RESETTLEMENT ZONE D",
            "APO RESETTLEMENT ZONE E",
            "DURUMI",
            "DURUMI PHASE 2",
            "GARKI AREA 1",
            "GARKI AREA 10",
            "GARKI AREA 11",
            "GARKI AREA 2",
            "GARKI AREA 3",
            "GARKI AREA 7",
            "GARKI AREA 8",
            "GWARINPA 1ST AVENUE",
            "GWARINPA 2ND AVENUE",
            "GWARINPA 3RD AVENUE",
            "GWARINPA 4TH AVENUE",
            "GWARINPA 5TH AVENUE",
            "GWARINPA 6TH AVENUE",
            "GWARINPA 7TH AVENUE",
            "GWARINPA EXTENSION",
            "KATAMPE EXTENSION",
            "KATAMPE MAIN",
            "KUBWA 2/1 PHASE 1",
            "KUBWA 2/2 PHASE 2",
            "KUBWA ARAB ROAD",
            "KUBWA BYAZHIN",
            "KUBWA EXTENSION 3",
            "KUBWA GBAZANGO",
            "KUBWA PHASE 3",
            "KUBWA PW",
            "KUBWA FCDA / FHA",
            "LIFE CAMP EXTENSION",
            "MABUSHI",
            "MAITAMA ALEIRO",
            "MAITAMA ASO DRIVE",
            "MAITAMA CENTRAL",
            "MAITAMA EXTENSION",
            "ASOKORO",
            "BWARI",
            "CENTRAL",
            "DAKIBIYU",
            "DAWAKI",
            "DEI DEI",
            "DUTSE",
            "EFAB",
            "GALADIMAWA",
            "GAMES VILLAGE",
            "GARKI 2",
            "GUDU",
            "GUZAPE",
            "GWAGWALADA",
            "JABI",
            "JAHI",
            "KABUSA",
            "KADO",
            "KARU",
            "KAURA DISTRICT",
            "KUJE",
            "LIFE CAMP",
            "LOKOGOMA",
            "LUGBE ACROSS ZONE 1 - 9",
            "LUGBE KAPWA",
            "LUGBE MR BIGGS",
            "LUGBE NEW SITE",
            "LUGBE PEACE VILLAGE",
            "LUGBE POLICE SIGN POST",
            "LUGBE PREMIER ACADEMY",
            "LUGBE SECTOR F",
            "LUGBE SKYE BANK",
            "LUGBE TOTAL",
            "LUGBE TUDUN WADA",
            "MARARABA",
            "NYANYA",
            "PRINCE AND PRINCESS",
            "SUNCITY",
            "SUNNY VALE",
            "UTAKO",
            "WUSE ZONE 1",
            "WUSE ZONE 2",
            "WUSE ZONE 3",
            "WUSE ZONE 4",
            "WUSE ZONE 5",
            "WUSE ZONE 6",
            "WUSE ZONE 7",
            "WUSE 11",
            "WUYE",
            "AIRPORT ROAD - IDDO",
            "AIRPORT ROAD KUCHINGORO / CHIKA/ PYAKASA",
            "AIRPORT ROAD SAUKA / TRADE MORE",
            "DUTSE",
            "GIDAN MANGORO",
            "GWAGWALADA",
            "IDU",
            "JIKOWYI",
            "KARIMO",
            "KARU",
            "KUBWA CENTRAL",
            "KWALI",
            "LUGBE",
            "MINISTERS HILL",
            "MPAPE",
            "NICON JUNCTION",
            "TUNGAN MAJE",
            "ZUBA",
        ],
        "gombe" => [
            "AKKO",
            "ARAWA",
            "ASHAKA",
            "BAJOGA",
            "BALANGA",
            "BARUNDE",
            "BCJ",
            "BILLIRI",
            "BOLARI",
            "BYPASS",
            "DUKKU",
            "FUNAKAYE",
            "GOMBE",
            "GRA",
            "JEKADA FARI",
            "KALTUNGO",
            "KASUWAN MATA",
            "KWAMI",
            "MALAMFIDI",
            "NAFADA",
            "NAYI NAWA",
            "ORJI QUARTERS",
            "PANTAMI",
            "SHONGOM",
            "STATE LOW COST",
            "TUDUN WADA",
            "TUNFERE",
            "YAMALTU / DEBA",
        ],
        "imo" => [
            "AMAKOHIA - AKWAKUMA",
            "EZINIHITTE",
            "IHIAGWA",
            "IHIALA",
            "IGUOCHI",
            "MBAISE",
            "NGOR OKPALA",
            "NWANGELE",
            "OBOWO",
            "OGUTA",
            "OKIGWE",
            "ORLU",
            "OWERRI - ALADINMA",
            "OWERRI - DOUGLAS",
            "OWERRI - IHIAGWA",
            "OWERRI - IKENEGBU",
            "OWERRI - IRETE",
            "OWERRI - NEKEDE",
            "OWERRI - ORJI",
            "OWERRI - PORT HARCOURT ROAD",
            "OWERRI - UMUNGUMA",
            "OWERRI - WETHERAL",
            "OWERRI - WORLD BANK",
        ],
        "jigawa" => [
            "DUTSE",
            "GUMEL",
            "HADEJA",
            "HADEJIA",
            "JAHUM",
            "JAHUN",
            "KAZAURE",
            "RINGIM",
        ],
        "kaduna" => [
            "AIRPORT",
            "ANGWAN SARIKI",
            "ANGWAN SARIKI / MALALI",
            "BARNAWA",
            "BY PASS",
            "CENTRAL MARKET",
            "CONSTITUTION ROAD",
            "GONI GORA",
            "GONI GORA / KURUMASHI",
            "IBBI",
            "INDEPENDENCE ROAD",
            "JAJI",
            "KABALA",
            "KACHIA",
            "KADUNA CENTRAL",
            "KAFANCHAN",
            "KAKURI",
            "KAKURI / TRIKANIA",
            "KAWO - KADUNA",
            "KIKINU",
            "KURUMASHI",
            "LOW COST",
            "MAKARFI",
            "MALALI",
            "NARAYI",
            "NDA",
            "NNPC",
            "NNCP",
            "REGACHUKU",
            "SABO",
            "SIGN BOARD",
            "STATION ROUNDABOUT",
            "TRIKANIA",
            "TUNDU WADA",
            "ZARIA",
        ],
        "kano" => [
            "AIRFORCE BASE / AIRPORT ROAD",
            "AUDU BAKO WAY",
            "BADARAWA",
            "BICHI",
            "BRIGADE",
            "BUK OLD SITE / NEW SITE",
            "COURT ROAD",
            "FAGGE",
            "FARM CENTRE",
            "GADAN KAYA",
            "GADUN ALBASU",
            "GAYA",
            "GORON DUTSE",
            "GWAMMAJA",
            "GYADI-GYADI / ZOO ROAD",
            "GYADI-GYADI / ZARIA ROAD",
            "HOTORO",
            "KABUGA",
            "KANO - NASSARAWA",
            "KANO CITY",
            "KARKASARA",
            "KATSINA ROAD",
            "KAWO-KANO",
            "MURTALA MOHAMMED WAY",
            "NASSARAWA GRA",
            "NO MANSLAND",
            "PANSHEKARA",
            "SABON GARI",
            "SALLARI",
            "SHARADA",
            "SHARADA / GWAMMAJA",
            "TARAUNI",
            "WUDIL",
            "YANKABA / HADEJIA ROAD",
            "ZARIA ROAD / NA'IBAWA",
            "ZOO ROAD",
        ],
        "katsina" => [
            "KATSINA TOWN",
            "KANO ROAD",
        ],
        "kebbi" => [
            "AMBRUSA",
            "ARGUNGU",
            "BIRNIN KEBBI",
        ],
        "kogi" => [
            "ABOBO",
            "AJAOKUTA",
            "ANKPA",
            "AYANGBA",
            "CBN",
            "FELELE",
            "GANAJA",
            "IDAH",
            "ITAKPE",
            "JINGBE",
            "KABBA",
            "LOKOJA CENTRAL LOCATIONS",
            "MAMMY MARKET",
            "OBAJANA",
            "OKENNE",
            "ZANGO",
        ],
        "kwara" => [
            "ASA",
            "BARUTEN",
            "EDU",
            "EKITI",
            "IFELODUN",
            "ILORIN - AGBOOBA - ADEWOLE ESTATE",
            "ILORIN - CHALLENGE - UITH",
            "ILORIN - GAA AKANBI - ASA DAM - GANMO",
            "ILORIN - SURULERE - OJA OBA - EMIR'S PALACE",
            "ILORIN - UNITY - NEW YIDI ROAD - STADIUM",
            "ILORIN - TAIWO - AIRPORT",
            "ILORIN - TANKE - UNILORIN - PIPELINE",
            "ILORIN EAST",
            "ILORIN WEST",
            "ILORIN CENTRAL",
            "IREPODUN",
            "ISIN",
            "KAIAMA",
            "MORO",
            "OFFA",
            "OKE ERO",
            "OYUN",
            "PATEGI",
        ],
        "lagos" => [
            "Abule Egba (Agbado Ijaye Road)",
            "Abule Egba (Ajasa Command Road)",
            "Abule Egba (Ajegunle)",
            "Abule Egba (Alagbado)",
            "Abule Egba (Alakuko)",
            "Abule Egba (Ekoro Road)",
            "Abule Egba (Meiran Road)",
            "Abule Egba (New Oko Oba)",
            "Abule Egba (Old Otta Road)",
            "Agbara",
            "Agege (Ajuwon Akute Road)",
            "Agege (Dopemu)",
            "Agege (Iju Road)",
            "Agege (Old Abeokuta Road)",
            "Agege (Old Otta Road)",
            "Agege (Orile Agege)",
            "Agiliti",
            "Agungi (Lekki)",
            "Ajao Estate",
            "Alfa Beach",
            "Amuwo",
            "Anthony Village",
            "Apapa (Ajegunle)",
            "Apapa (Amukoko)",
            "Apapa (GRA)",
            "Apapa (Kiri Kiri)",
            "Apapa (Olodi)",
            "Apapa (Suru Alaba)",
            "Apapa (Tin Can)",
            "Apapa (Wharf Road)",
            "Awoyaya",
            "Awoyaya - Container Bus Stop",
            "Awoyaya - Eko Akete Estate",
            "Awoyaya - Epetu",
            "Awoyaya - Gbetu Iwerekun Road",
            "Awoyaya - Idowu Eletu",
            "Awoyaya - Mayfair Gardens",
            "Awoyaya - Ogunlana Bus Stop",
            "Awoyaya - Ologunfe",
            "Awoyaya - Oribanwa",
            "Badagry",
            "Berger",
            "Bogije",
            "Coker",
            "Doyin",
            "Ejigbo-Ailegun Road",
            "Ejigbo-Bucknor",
            "Ejigbo-Ile Epo",
            "Ejigbo-Isheri Osun",
            "Ejigbo-Jakande Wood Market",
            "Ejigbo-NNPC Road",
            "Ejigbo-Oke-Afa",
            "Ejigbo-Pipeline",
            "Ejigbo-Powerline",
            "Elemoro",
            "Epe",
            "Fagba (Iju Road)",
            "Festac - 1st Avenue",
            "Festac - 2nd Avenue",
            "Festac - 3rd Avenue",
            "Festac - 4th Avenue",
            "Festac - 5th Avenue",
            "Festac - 6th Avenue",
            "Festac - 7th Avenue",
            "Gbagada - Ifako",
            "Gbagada - Abule Okuta",
            "Gbagada - Araromi",
            "Gbagada - Deeper Life",
            "Gbagada - Diya",
            "Gbagada - Expressway",
            "Gbagada - Hospital",
            "Gbagada - L&K",
            "Gbagada - New Garage",
            "Gbagada - Olopomeji",
            "Gbagada - Pedro",
            "Gbagada - Sawmill",
            "Gbagada - Sholuyi",
            "Ibeju-Lekki",
            "Idimu",
            "Igando",
            "Ijanikin",
            "Ijegun Ikotun",
            "Ijegun - Obadore Road",
            "Ijora",
            "Ikeja - Adeniyi Jones",
            "Ikeja - Alausa",
            "Ikeja - Allen Avenue",
            "Ikeja - Computer Village",
            "Ikeja - GRA",
            "Ikeja - MM Airport",
            "Ikeja - Mangoro",
            "Ikeja - Oba Akran",
            "Ikeja - Opebi",
            "Ikorodu - Adamo",
            "Ikorodu - Agbede",
            "Ikorodu - Agbowa",
            "Ikorodu - Agric",
            "Ikorodu - Bayeku",
            "Ikorodu - Eyita",
            "Ikorodu - Gberigbe",
            "Ikorodu - Ijede",
            "Ikorodu - Imota",
            "Ikorodu - Ita Oluwo",
            "Ikorodu - Itamaga",
            "Ikorodu - Offin",
            "Ikorodu - Owode-Ibese",
            "Ikorodu Road - Ajegunle",
            "Ikorodu Road - Irawo",
            "Ikorodu Road - Owode Onirin",
            "Ikorodu - Elepe",
            "Ikorodu - Laspotech",
            "Ikorodu - Ogolonto",
            "Ikorodu - Sabo",
            "Ikorodu - Imota Caleb University",
            "Ikorodu - Agufoye",
            "Ikorodu - Benson",
            "Ikorodu - Garage",
            "Ikorodu - Odokekere",
            "Ikorodu - Odonla",
            "Ikorodu - Ogijo",
            "Ikota",
            "Ikorun",
            "Ikoyi - Awolowo Road",
            "Ikoyi - Bourdillon",
            "Ikoyi - Dolphin",
            "Ikoyi - Glover Road",
            "Ikoyi - Keffi",
            "Ikoyi - Kings Way Road",
            "Ikoyi - Obalende",
            "Ikoyi - Queens Drive",
            "Ikoyi MTN - Pickup Station",
            "Ilaje - Bariga",
            "Ilupeji - Lagos",
            "Isheri Ikotun",
            "Isheri Magodo",
            "Isolo",
            "Iyana Ejigbo",
            "Iyana Iba",
            "Iyana Ipaja - Abesan",
            "Iyana Ipaja - Aboru",
            "Iyana Ipaja - Ayobo Road",
            "Iyana Ipaja - Command Road",
            "Iyana Ipaja - Egbeda",
            "Iyana Ipaja - Ikola Road",
            "Iyana Ipaja - Iyana Ipaja Road",
            "Iyana Ipaja - Shasha",
            "Jakande - Lekki",
            "Jakande - Isolo",
            "Ketu - Agboyi",
            "Ketu - Alapere",
            "Ketu - CMD Road",
            "Ketu - Demurin",
            "Ketu-Ikosi Road",
            "Ketu-Ile Ile",
            "Ketu - Iyana School",
            "Ketu - Tipper Garage",
            "Lagos Island - Adeniji",
            "Lagos Island - Marina",
            "Lagos Island - Onikan",
            "Lagos Island - Sura",
            "Lagos Island - TBS",
            "Lakowe",
            "Lakowe - Adeba Road",
            "Lakowe - Golf",
            "Lakowe - Kajola",
            "Lakowe - School Gate",
            "Lekki - VGC",
            "Lekki 1 - Bishop Durosimi",
            "Lekki 1 - F.T.Kuboye Street",
            "Lekki 1 - Omorinre Johnson",
            "Lekki Phase 1 - Admiralty Road",
            "Lekki Phase 1 - Admiralty Way",
            "Lekki Phase 1 - Fola Osibo",
            "Lekki - Agungi",
            "Lekki-Ajah -  Abijo",
            "Lekki-Ajah -  Addo Road",
            "Lekki-Ajah - Badore",
            "Lekki-Ajah - Ilaje",
            "Lekki-Ajah - Ilasan",
            "Lekki-Ajah - Jakande",
            "Lekki-Ajah - Sangotedo",
            "Lekki-Awoyaya",
            "Lekki-Chisco",
            "Lekki-Elf",
            "Lekki-Igboefon",
            "Lekki-Ikate Elegushi",
            "Lekki-Jakande - Kazeem Eletu",
            "Lekki-Maruwa",
            "Lekki - Oniru Estate",
            "Lekki - Osapa London",
            "Magboro",
            "Magodo",
            "Maryland - Mende",
            "Maryland - Onigbongbo",
            "Mebanmu",
            "Mile 12",
            "Mile 12 - Ajelogo",
            "Mile 12 - Agboyi Ketu",
            "Mile 12 - Doyin Omololu",
            "Mile 12 - Orishigun",
            "Mile 2",
            "Mushin - Palm Avenue",
            "Mushin - Agege Motor Road",
            "Mushin - Daleko Market",
            "Mushin - Fatai Atere",
            "Mushin - Idi Oro",
            "Mushin - Idi-Araba",
            "Mushin - Ilasamaja Road",
            "Mushin - Isolo Road",
            "Mushin - Ladipo Road",
            "Mushin - Mushin Market",
            "Mushin - Olateju",
            "Mushin - Papa Ajao",
            "Odongunyan",
            "Ogba - Akilo Road",
            "Ogba - College Road",
            "Ogba - Lateef Jakande Road",
            "Ogba - Acme Road",
            "Ogba - Aguda",
            "Ogba - County",
            "Ogba - Ifako-Idiagbon",
            "Ogba - Ifako-Orimolade",
            "Ogba - Isheri Road",
            "Ogba - Obawole",
            "Ogba - Ojodu",
            "Ogba - Oke-Ira",
            "Ogba - Oke-Ira 2nd Junction",
            "Ogba - Surulere Ind Road",
            "Ogba - Wemco Road",
            "Ogudu",
            "Ojo",
            "Ojo Shibiri",
            "Ojo-Abule Oshun",
            "Ojo-Adaloko",
            "Ojo-Agric",
            "Ojo-Ajangbadi",
            "Ojo - Alaba International",
            "Ojo - Alaba Rago",
            "Ojo - Alaba Suru",
            "Ojo - Alaba Alakija",
            "Ojo - Cassidy",
            "Ojo - Ijegun",
            "Ojo - Ilogbo",
            "Ojo - Ojo Barracks",
            "Ojo - Okokomaiko",
            "Ojo - Old Ojo Road",
            "Ojo - Onireke",
            "Ojo - PPL",
            "Ojo - Shibiri",
            "Ojo - Tedi Town",
            "Ojo - Trade Fair",
            "Ojo - Volks",
            "Ojodu",
            "Ojokoro",
            "Ojota",
            "Okokomaiko",
            "Okota",
            "Omole Phase 1",
            "Omole Phase 2",
            "Oregun",
            "Oreyo-Igbe",
            "Orile",
            "Osapa - Lekki",
            "Oshodi-Bolade",
            "Oshodi-Isolo",
            "Oshodi-Mafoluku",
            "Oshodi-Orile",
            "Oshodi-Shogunle",
            "Palmgrove - Onipanu",
            "Sari - Iganmu",
            "Satelite Town",
            "Somolu",
            "Surulere - Adeniran Ogunsanya",
            "Surulere - Aguda",
            "Surulere - Bode Thomas",
            "Surulere - Fatia Shitta",
            "Surulere - Idi Araba",
            "Surulere - Ijesha",
            "Surulere - Iponri",
            "Surulere - Itire",
            "Surulere - Lawanson",
            "Surulere - Masha",
            "Surulere - Ogunlana drive",
            "Surulere - Ojuelegba",
            "VI - Adetokunbo Ademola",
            "VI - Ahmadu Bello Way",
            "VI - Bishop Aboyade Cole",
            "VI - Ajose Adeogun",
            "VI - Akin Adeshola",
            "VI - Bishop Oluwale",
            "VI - Yusuf Abiodun",
            "VI - Adeola Odeku",
            "VI - Kofo Abayomi",
            "Yaba - Abula Ijesha",
            "Yaba - Fadeyi",
            "Yaba - Sabo",
            "Yaba - UNILAG",
            "Yaba - Abula Oja",
            "Yaba - Adekunle",
            "Yaba - Akoka",
            "Yaba - Alagomeju",
            "Yaba - College of Education",
            "Yaba - Commercial Avenue",
            "Yaba Folagoro",
            "Yaba - Herbert Macaulay Way",
            "Yaba - Jibowu",
            "Yaba - makoko",
            "Yaba - Murtala Muhammed Way",
            "Yaba - Onike Iwaya",
            "Yaba - Oyingbo",
            "Yaba - Tejuosho",
            "Yaba - University Road",
            "Yaba - YabaTech",
        ],
        "nasarawa" => [
            "AKWANGA",
            "AWE",
            "DOMA",
            "KARU",
            "KEANA",
            "KEFFI",
            "LAFIA - BUKAN SIDI",
            "LAFIA CENTRAL LOCATIONS",
            "LAFIA - COLLEGE / POLYTECHNIC",
            "LAFIA EAST",
            "LAFIA - JOS ROAD",
            "LAFIA - LOW COST",
            "LAFIA - SABON PEGI",
            "LAFIA - SHABU",
            "LAFIA - TUDUN GWANDARA",
            "MASAKA",
            "NASARAWA",
            "NASARAWA EGON",
            "NEW KARU",
            "OBI",
            "TOTO",
            "WAMBA",
        ],
        "niger" => [
            "AGAI",
            "BADDEGI",
            "BIDA",
            "KONTAGORA",
            "LAPAI",
            "MADALA",
            "MINNA -BOSSO",
            "MINNA CENTRAL",
            "MINNA - CHANCHAGA",
            "MINNA - DAVID MARK WAY",
            "MINNA - DUTSEN KURA",
            "MINNA - EASTERN BYPASS",
            "MINNA - F LAYOUT",
            "MINNA - FADIPE",
            "MINNA - FARM CENTER",
            "MINNA - GIDAN KWANO",
            "MINNA - GRA",
            "MINNA - KPAKUNGU",
            "MINNA - KURE MARKET",
            "MINNA - KUTA ROAD",
            "MINNA - LONDON STREET",
            "MINNA - M.I. WUSHISHI",
            "MINNA - MAIKUNKELE",
            "MINNA - MAITUMBI",
            "MINNA - MANDELA",
            "MINNA - MOBIL",
            "MINNA - OKADA WAY",
            "MINNA - SANGO",
            "MINNA - SAUKA KA HUTA",
            "MINNA - SHIRORO WAY",
            "MINNA - TUNGA",
            "MINNA - WESTERN BYPASS",
            "SULEJA",
            "SULEJA - GURAKA",
            "SULEJA - KWAMBA",
            "SULEJA - KWANKASHE",
            "SULEJA - MAJE",
            "SULEJA - RAFINSANYI",
            "ZUBA",
        ],
        "ogun" => [
            "ABEOKUTA - ADIGBE",
            "ABEOKUTA - CENTRAL",
            "ABEOKUTA - ELEGA",
            "ABEOKUTA - IDI ABA",
            "ABEOKUTA - LAFENWA",
            "ABEOKUTA - MKO ABIOLA WAY",
            "ABEOKUTA - OKE MOSAN",
            "AGBARA - OPIC",
            "AGBARA ESTATE - OGUN",
            "AGO IWOYE",
            "AKUTE - OGUN",
            "EWEKORO",
            "IFO",
            "IGBESA - CROWFORD UNIVERSITY",
            "IGBESA - IGBESA POLYTECHNIC",
            "IGBESA - LUSADA",
            "IJEBU IFE",
            "IJEBU IGBO",
            "IJEBU NORTH EAST",
            "IJEBU ODE - AWUJAALE STREET",
            "IJEBU ODE - FOLAGBADE",
            "IJEBU ODE - MOLIPA",
            "IJEBU ODE - ASIRU",
            "IJEBU ODE - BONAJO",
            "IJEBU ODE - DEGUN",
            "IJEBU ODE - IBADAN ROAD",
            "IJEBU ODE - IGBEBA ROAD",
            "IJEBU ODE - ITALAPO",
            "IJEBU ODE - NEW ROAD",
            "IJEBU ODE - OLISA STREET",
            "IJEBU ODE - OSINUBI",
            "IJEBU ODE - SABO",
            "IJEBU ODE - SAKA",
            "IJEBU ODE - TUABOAT ROAD",
            "IJEBU ODE - LEKUTI",
            "IKENNE",
            "ILARO - AJILETE",
            "ILARO - IBESE",
            "ILARO - IKOSI",
            "ILARO - LESLEI ROAD",
            "ILARO - OKE ELA",
            "ILARO - OKE ODAN",
            "ILARO - ORITA",
            "ILARO - PAPA LANTO",
            "ILISHAN REMO - BABCOCK",
            "IMEKO AFON",
            "ITELE - IJEBU",
            "MOWE IBAFO",
            "OBA",
            "OBAFEMI OWODE",
            "OBANTOKO",
            "ODEDA",
            "ODOGBOLU",
            "OGIJO",
            "OGUN - SAGAMU - REMO",
            "ORU",
            "OTTA TOWN - AKEJA NAVY",
            "OTTA TOWN - BELLS",
            "OTTA TOWN - COVENANT",
            "OTTA TOWN - IFO",
            "OTTA TOWN - OBASANJO",
            "OTTA TOWN - OSI OLOSUN",
            "OTTA TOWN - OWODE",
            "REDEEMED CAMP",
            "REMO NORTH",
            "SANGO - IJOKO",
            "SANTO OTTA - ATAN",
            "SANTO OTTA - IJU",
            "SANGO OTTA - OJU ORE",
            "SANGO OTTA - SANGO",
            "SANGO OTTA - TOLL GATE",
            "YEWA NORTH",
            "YEWA SOUTH",
        ],
        "ondo" => [
            "AKOKO",
            "AKURE OSHILE",
            "AKURE - ALAGBAKA",
            "AKURE - FUTA",
            "AKURE - IDANRE ROAD",
            "AKURE - IGBATORO",
            "AKURE - IJAPO ESTATE",
            "AKURE - IJARE",
            "AKURE - IJOKA",
            "AKURE - ILARA MOKIN",
            "AKURE - ILESHA GARAGE",
            "AKURE - OBA ADESIDA",
            "AKURE - OBA ILE",
            "AKURE - ODA ROAD",
            "AKURE - OLUWATUYI",
            "AKURE - ONDO ROAD",
            "AKURE - OYEMEKUN ROAD",
            "AKURE - SHAGARI VILLAGE",
            "ESE ODO",
            "IDANRE",
            "IFEDORE",
            "IGBOKODA",
            "ILLAJE",
            "IRELE",
            "ODIGBO",
            "OKITIPUPA",
            "ONDO TOWN - SAGUN",
            "ONDO TOWN - YABA",
            "ONDO TOWN - AJEGUNLE",
            "ONDO TOWN - AJEMULEGUN",
            "ONDO TOWN - MIMIKO ESTATE",
            "ONDO TOWN - OKA",
            "ONDO TOWN - AKUNGBA",
            "ONDO TOWN - AKINJAGULAR",
            "ONDO TOWN - AYEYEMI",
            "ORE",
            "OSE",
            "OWO",
        ],
        "osun" => [
            "ARAKEJI",
            "EDE",
            "EJIGBO",
            "EJIGBO - OSUN",
            "ESAOKE",
            "IJEBU",
            "IJEBU - JESA",
            "IKIRE",
            "IKIRUN",
            "ILA",
            "ILA - ORUNGUN",
            "ILE IFE",
            "ILE IFE - ADESANMI",
            "ILE IFE - AJEBAMIDELE",
            "ILE IFE - AKARABATA",
            "ILE IFE - AP",
            "ILE IFE - ASERIFA",
            "ILE IFE - AWOYEKU",
            "ILE IFE - EDE ROAD",
            "ILE IFE - ELEYELE",
            "ILE IFE - ILESA GARAGE / OAUTH",
            "ILE IFE - IREMO",
            "ILE IFE - MAYFAIR",
            "ILE IFE - MODOMO",
            "ILE IFE - MOKURO",
            "ILE IFE - MORO / EDUNABON / IPETUMODU",
            "ILE IFE - NTA",
            "ILE IFE - OAU COMMUNITY",
            "ILE IFE - ODUDUWA UNIVERSITY",
            "ILE IFE - OKE D.O.",
            "ILE IFE - OMOLE",
            "ILE IFE - OPA",
            "ILE IFE - OUR LADY'S MODAKEKE",
            "ILE IFE - PARAKIN",
            "ILE IFE - POST OFFICE / SABO",
            "ILE IFE - LAGERE",
            "ILESHA",
            "ILOKO",
            "IREE",
            "IWO",
            "IWO - OSUN",
            "MORO / EDUNABON / IPETUMODU",
            "OAU COMMUNITY",
            "OKUKU",
            "OSHOGBO",
            "OSHOGBO CENTRAL LOCATIONS",
            "OSOGBO",
            "OSOGBO - AGUNBELEWO",
            "OSOGBO - DADA ESTATE",
            "OSOGBO - IGBONA",
            "OSOGBO - KOBO",
            "OSOGBO - OFATEDO",
            "OSOGBO - OGO OLUWA",
            "OSOGBO - OKE BAALE",
            "OSOGBO - OKEFIA",
            "OSOGBO - ORISUNMIBARE",
            "OSOGBO - OTA - EFUN",
            "OSOGBO - POWERLINE",
            "OSOGBO - RING ROAD",
        ],
        "oyo" => [
            "AFIJIO",
            "AKINYELE",
            "ALOMOJA",
            "ATIBA",
            "ATISBO",
            "EGBEDA - OYO",
            "ERUWA",
            "IBADAN - AGODI",
            "IBADAN - AJIBODE",
            "IBADAN - AKOBO",
            "IBADAN - ALAKIA",
            "IBADAN - APATA",
            "IBADAN - BODIJA",
            "IBADAN - CHALLENGE",
            "IBADAN - DUGBE",
            "IBADAN - ELEBU",
            "IBADAN - ELEYELE",
            "IBADAN - IDI APE - ASHI",
            "IBADAN - IWO ROAD",
            "IBADAN - JERICHO",
            "IBADAN - LALUPON",
            "IBADAN - MOLETE",
            "IBADAN - MONANTAN",
            "IBADAN - MONIYA",
            "IBADAN - NORTH WEST",
            "IBADAN - ODO ONA",
            "IBADAN - OJOO",
            "IBADAN - OLODO",
            "IBADAN - OLOHUNDA",
            "IBADAN - OLORUNSOGO",
            "IBADAN - OLUYOLE",
            "IBADAN - RING ROAD",
            "IBADAN - SOKA",
            "IBADAN - TOSE",
            "IBADAN - UI",
            "IBARAPA",
            "IDI IROKO",
            "IDO",
            "IGBETI",
            "IGBO OLOYIN",
            "IREPO",
            "ISEBO",
            "ISEYIN",
            "ITESIWAJU",
            "IWAJOWA",
            "IWO - OYO",
            "IWO ROAD - OLORUNSOGO",
            "KAJOLA",
            "LAGELU",
            "LALUPON",
            "LANLATE",
            "MONIYA",
            "OGBOMOSHO",
            "OGO OLUWA",
            "OLOGUN ERU",
            "OLORUNSOGO",
            "ONA ARA",
            "ORELOPE",
            "ORI IRE",
            "OYO TOWN - ADODONGBO",
            "OYO TOWN - AKINMORIN",
            "OYO TOWN - ARAROMI",
            "OYO TOWN - FOLA TYRE",
            "OYO TOWN - ISOKUN",
            "OYO TOWN - JOBELE",
            "OYO TOWN - MABOLAJE",
            "OYO TOWN - NEW CELE",
            "OYO TOWN - OROKI",
            "OYO TOWN - SAKI",
            "SAGBE",
            "SURULERE",
        ],
        "plateau" => [
            "AHMADU BELLO WAY",
            "BARIKIN LADI",
            "BARKIN LADI",
            "BAUCHI ROAD",
            "BUKURU",
            "DADIN KOWA",
            "FARIN GADA",
            "HAIPANG",
            "JOS SOUTH",
            "KATAKO",
            "KURU",
            "LAMIGO",
            "MANGU",
            "NASARAWA",
            "OLA AIRPORT ROAD",
            "PLATEAU - NASARAWA",
            "PLATEAU - ZARIA ROAD",
            "PLATEAU - MURTALA MUHAMMED WAY",
            "RAYFIELD",
            "RAYFIELD / DADIN KOWA",
            "RUKUBA ROAD",
            "SECRETARIAT JUNCTION",
            "TINA JUNCTION",
            "VOM",
            "ZARIA ROAD",
            "ZARMAGANDA",
            "ZAWAN",
            "ZAWAN / BUKURU",
        ],
        "rivers" => [
            "ABHONEMA",
            "AHOADA",
            "AIRPORT ROAD - PORT HARCOURT",
            "BONNY ISLAND",
            "ELELE",
            "ELELEWON",
            "ELEME - AGBONCHIA",
            "ELEME - AKPAJO",
            "ELEME - ALESA",
            "ELEME - ALETO",
            "ELEME - ALODE",
            "ELEME - EBUBU",
            "ELEME - EKPORO",
            "ELEME - ETEO",
            "ELEME - NCHIA",
            "ELEME - ODIDO",
            "ELEME - OGALE",
            "ELEME - ONNE",
            "EMOUHA",
            "ETCHE",
            "ISIOKPO",
            "OKRIKA",
            "OKRIKA - OKRIKA TOWN - KIRIKE",
            "OMOKU",
            "OYIGBO - AFAM",
            "OYIGBO - EGBERU",
            "OYIGBO -IZUOMA",
            "OYIGBO - KOMKOM",
            "OYIGBO - MIRINWANYI",
            "OYIGBO - NDOKI",
            "OYIGBO - OBEAMA",
            "OYIGBO - UMUAGBAI",
            "PHC - NEW GRA - PHASE 1",
            "PHC - NEW GRA - PHASE 2",
            "PHC - NEW GRA - PHASE 3",
            "PHC - NEW GRA - PHASE 4",
            "PHC - RIVERS STATE UNIVERSITY",
            "PHC - WOJI CENTRAL LOCATION",
            "PORT HARCOURT - ABONNEMA TOWN",
            "PORT HARCOURT - ABONNEMA WHARF",
            "PORT HARCOURT - ABULOMA",
            "PORT HARCOURT - ADA GEORGE",
            "PORT HARCOURT - AGIP",
            "PORT HARCOURT - AIRFORCE BASE",
            "PORT HARCOURT - AKPAJO",
            "PORT HARCOURT - ALAKAHIA - UPTH",
            "PORT HARCOURT - ALUU",
            "PORT HARCOURT - AMADIA AMA",
            "PORT HARCOURT - AYA - OGOL OGO",
            "PORT HARCOURT - AZUBIE",
            "PORT HARCOURT - BORI CAMP",
            "PORT HARCOURT - BOROKIRI",
            "PORT HARCOURT - CHOBA",
            "PORT HARCOURT - CHOBA - UNIPORT",
            "PORT HARCOURT - D / LINE",
            "PORT HARCOURT - DARICK POLO",
            "PORT HARCOURT - DIOBU",
            "PORT HARCOURT - EAGLE ISLAND",
            "PORT HARCOURT - EGBELU",
            "PORT HARCOURT - ELEKAHIA",
            "PORT HARCOURT - ELELEWON",
            "PORT HARCOURT - ELIBOLO",
            "PORT HARCOURT - ELIGBAM",
            "PORT HARCOURT - ELIMGBU",
            "PORT HARCOURT - ELINPARAWON",
            "PORT HARCOURT - ELIOHANI",
            "PORT HARCOURT - ELIOZU",
            "PORT HARCOURT - ENEKA",
            "PORT HARCOURT - IGWURUTA",
            "PORT HARCOURT - INTELS KM 16",
            "PORT HARCOURT - MGBUOBA",
            "PORT HARCOURT - MILE 1",
            "PORT HARCOURT - MILE 2",
            "PORT HARCOURT - MILE 3",
            "PORT HARCOURT - MILE 4",
            "PORT HARCOURT - MILE 5",
            "PORT HARCOURT - MUGBUOSIMINI",
            "PORT HARCOURT - NEW GRA - TOMBIA",
            "PORT HARCOURT - NKPOGU",
            "PORT HARCOURT - NKPOLU",
            "PORT HARCOURT - OGBATAI",
            "PORT HARCOURT - OGBOGORO",
            "PORT HARCOURT - OGBUNABALI",
            "PORT HARCOURT - OGUNIGBA",
            "PORT HARCOURT - OKPORO ROAD",
            "PORT HARCOURT - OKURU",
            "PORT HARCOURT - OLD GRA",
            "PORT HARCOURT - ORAZI",
            "PORT HARCOURT - OZUBOKO",
            "PORT HARCOURT - PETER ODILI ROAD",
            "PORT HARCOURT - RECLAMATION",
            "PORT HARCOURT - RUKPOKWU",
            "PORT HARCOURT - RUMEME",
            "PORT HARCOURT - RUMUAGHAOLU",
            "PORT HARCOURT - RUMUAKPAKOLOSI",
            "PORT HARCOURT - RUMUEPIRIKOM",
            "PORT HARCOURT - RUMUEVOLU",
            "PORT HARCOURT - RUMUIBEKWE",
            "PORT HARCOURT - RUMUIGBO",
            "PORT HARCOURT - RUMUKALAGBOR",
            "PORT HARCOURT - RUMUKRUSHI",
            "PORT HARCOURT - RUMUMASI",
            "PORT HARCOURT - RUMUODUMAYA",
            "PORT HARCOURT - RUMUOKE",
            "PORT HARCOURT - RUMUOGBA",
            "PORT HARCOURT - RUMUOKORO",
            "PORT HARCOURT - RUMUOKWUTA",
            "PORT HARCOURT - RUMUOLA",
            "PORT HARCOURT - RUMUOLUMENI",
            "PORT HARCOURT - RUMUOROSI",
            "PORT HARCOURT - RUMUOWAH",
            "PORT HARCOURT - STADIUM ROAD",
            "PORT HARCOURT - TOWN",
            "PORT HARCOURT - TRANS AMADI",
            "PORT HARCOURT - WOJIILLOM",
            "PORT HARCOURT - WOJI ROAD",
            "PORT HARCOURT - WOJI KYC",
            "PORT HARCOURT - WOJI ELIJIJI",
            "RUMUAGHOLU",
            "RUMUODUOMAYA",
        ],
        "sokoto" => [
            "SOKOTO TOWN",
            "SOKOTO TOWN CENTRAL LOCATIONS",
            "SOKOTO - CENTRAL LOCATION",
            "SOKOTO / GUSAU",
        ],
        "taraba" => [
            "JALINGO TOWN",
            "YOLA ROAD",
        ],
        "yobe" => [
            "BADE",
            "FIKA",
            "GASHUA",
            "GEIDAM",
            "NGURU",
        ],
        "zamfara" => ["ZAMFARA TOWN"],
    );
}

function sweetAlert($text, $title, $icon = "success", $button = false, $timer = 5000): array
{
    return [
        'icon' => $icon,
        'text' => $text,
        'title' => $title,
        'showConfirmButton' => $button,
        'timer' => $timer,
    ];
}

function formatMoney(int $amount): string
{
    if ($amount >= 1000000000) {
        return round($amount / 1000000000, 1) . 'b';
    } elseif ($amount >= 1000000) {
        return round($amount / 1000000, 1) . 'm';
    } elseif ($amount >= 1000) {
        return round($amount / 1000, 1) . 'k';
    } else {
        return $amount;
    }

}

function paginationLevel(int $total): array
{
    // if ($total >= 1000) {
    //     return [5, 10, 20, 50, 100, 200, 500, 1000, 2000];
    // } else if ($total >= 100) {
    //     return [5, 10, 20, 50, 100, 200, 500];
    // } else {
    //     return [5, 10, 20, 50, 100];
    // }
    return [5, 10, 20, 50, 100];
}
